Frontend/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Common.Enum;
using Common.Messages;
using Common.Messages.Customer;
using Common.Messages.Rent;
using Frontend.Context;
using Frontend.Helpers.Alert;
using Frontend.Helpers.Exception;
using Frontend.Helpers.Rental;
using Frontend.Models;
using Frontend.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace Frontend.Controllers
{
    [ServiceFilter(typeof(ExceptionHandler))]
    public class CartController : Controller
    {
        private readonly INServiceBusRequester<Message> _nServiceBusRequester;
        private readonly DataContext _dataContext;
        private readonly IMapper _mapper;

        public CartController(INServiceBusRequester<Message> nServiceBusRequester, DataContext dataContext, IMapper mapper)
        {
            this._nServiceBusRequester = nServiceBusRequester;
            this._dataContext = dataContext;
            this._mapper = mapper;
        }
         
        public async Task<ActionResult> Index()
        {
            var carts = await _dataContext.Carts.Where(x=>x.UserName== UserDetails.UserName).ToListAsync();
            return View(carts);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(List<Cart> carts)
        {
            if (ModelState.IsValid)
            {
                var rentCreates = _mapper.Map<List<RentCreated>>(carts);

                CustomerRent customerRent = new CustomerRent();
                customerRent.CustomerName = UserDetails.UserName;
                customerRent.RentCreated = rentCreates;

                var message = new Message();
                message.Id = Guid.NewGuid();
                message.RequestType = RequestType.RentCreate;
                message.Content = JsonConvert.SerializeObject(customerRent);

                var response = await _nServiceBusRequester.GetMessage(message);
                var created = JsonConvert.DeserializeObject<bool>(response.Content);                 
                if(created)
                {
                    _dataContext.RemoveRange(await _dataContext.Carts.ToListAsync());
                     await _dataContext.SaveChangesAsync();
                    
                     return RedirectToAction(nameof(Index)).AlertSuccess("Success", "Your process has been completed successfully.");                
                }
                 
            }

            return View().AlertDanger("Error", "Your transaction was not completed successfully.");
        }       
        

        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {        
             var order = await _dataContext.Carts.FirstOrDefaultAsync(t => t.Id == id);               
             return View(order);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRecord(int id)
        {
            var order = await _dataContext.Carts.FirstOrDefaultAsync(t => t.Id == id);
            if (order != null)
            {
                _dataContext.Carts.Remove(order);
                int save =  await _dataContext.SaveChangesAsync();
                if (save > 0)
                {
                    return RedirectToAction(nameof(Index)).AlertSuccess("Success", "Your process has been completed successfully.");
                }
            }

            return View().AlertDanger("Error", "Your transaction was not completed successfully.");
        }

    }
}

Frontend/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Common.Enum;
using Common.Messages;
using Common.Messages.Invoice;
using Common.Models;
using Frontend.Helpers.Alert;
using Frontend.Helpers.Exception;
using Frontend.Helpers.Rental;
using Frontend.Models;
using Frontend.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Frontend.Controllers
{
    [ServiceFilter(typeof(ExceptionHandler))]
    public class InvoiceController : Controller
    {
        private readonly INServiceBusRequester<Message> _nServiceBusRequester;
        private readonly IMapper _mapper;

        public InvoiceController(INServiceBusRequester<Message> nServiceBusRequester, IMapper mapper)
        {
            this._nServiceBusRequester = nServiceBusRequester;
            this._mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var message = new Message();
            message.Id = Guid.NewGuid();
            message.RequestType = RequestType.GetInvoiceList;
            message.Content = JsonConvert.SerializeObject(new GetInvoice() { UserName = UserDetails.UserName });
            var response = await _nServiceBusRequester.GetMessage(message);
            if(response.IsSucceded)
            {
                var invoices = JsonConvert.DeserializeObject<List<Rent>>(response.Content);
                 
                var invoiceRecords = _mapper.Map<List<InvoiceViewModel>>(invoices);
                return View(invoiceRecords);
            }

            return View().AlertDanger("Error", "Your request couldn't processed.");

        }

        [HttpPost]
        public async Task<IActionResult> Index(int id)
        {
            if (ModelState.IsValid)
            {
                var message = new Message();
                message.Id = Guid.NewGuid();
                message.RequestType = RequestType.GetInvoice;
                message.Content = JsonConvert.SerializeObject(new GetInvoice() { UserName = UserDetails.UserName, RentId = id });
                var response = await _nServiceBusRequester.GetMessage(message);
                if (response.IsSucceded)
                {
                    var invoice = JsonConvert.DeserializeObject<Rent>(response.Content);
                    string invoiceRaw =   invoice.GenerateInvoce();
                    var content = Encoding.UTF8.GetBytes(invoiceRaw);

                    return File(content, "text/plain", "Invoice.txt");
                }

                return View().AlertDanger("Error", "Your request couldn't processed.");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Frontend/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Common.Enum;
using Common.Messages;
using Common.Messages.Inventory;
using Common.Models;
using Frontend.Context;
using Frontend.Models; 
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Frontend.Services;
using System.Text;
using Frontend.Helpers.Alert;
using Frontend.Helpers.Exception;

namespace Frontend.Controllers
{
    [ServiceFilter(typeof(ExceptionHandler))]
    public class RentController : Controller
    {
        private readonly INServiceBusRequester<Message> _nServiceBusRequester;
        private readonly IMapper _mapper;
        private readonly DataContext _dataContext;

        public RentController(INServiceBusRequester<Message> nServiceBusRequester, IMapper mapper, DataContext dataContext)
        {
            this._nServiceBusRequester = nServiceBusRequester;
            this._mapper = mapper;
            this._dataContext = dataContext;
        }

        public async Task<IActionResult> Index()
        {
            var message = new Message();
            message.Id = Guid.NewGuid();
            message.RequestType = RequestType.InventoryList;
            message.Content = JsonConvert.SerializeObject(new InventoryRequest());
            var response = await _nServiceBusRequester.GetMessage(message);
            var inventories = JsonConvert.DeserializeObject<List<Inventory>>(response.Content);

            var listview = _mapper.Map<List<RentViewModel>>(inventories);

            return View(listview);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Index(List<RentViewModel> rentViewModels)
        {

            if (ModelState.IsValid)
            {
                var selectedModels = rentViewModels.Where(x => x.IsChecked == true).ToList();
                var cartDetails = _mapper.Map<List<Cart>>(selectedModels);

                await _dataContext.Carts.AddRangeAsync(cartDetails);

                int save = await _dataContext.SaveChangesAsync();
                if (save > 0)
                {
                    return RedirectToAction(nameof(Index)).AlertSuccess("Success", "Your process has been completed successfully.");
                }

            }

            var errors = ModelState.Values.SelectMany(x => x.Errors).Select(e => e.ErrorMessage);

            var builder = new StringBuilder();

            foreach (var error in errors)
            {
                builder.Append(error);
            }

            return RedirectToAction(nameof(Index)).AlertDanger("Error", builder.ToString());
             
        }
    }
}

Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] - Frontend</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @*<partial name="_CookieConsentPartial" />*@ 

    <div class="d-flex" id="wrapper">
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading"> <span class="glyphicon glyphicon-bookmark"></span>Renting Construction</div>
            <div class="list-group list-group-flush">
                
                <a asp-area="" class="list-group-item list-group-item-action bg-light" asp-controller="Rent" asp-action="Index">Rent</a> 
                <a asp-area="" class="list-group-item list-group-item-action bg-light" asp-controller="Invoice" asp-action="Index">My Invoices</a> 
            </div>
        </div>         
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="btn btn-primary" asp-controller="Cart" asp-action="Index">My Renting Cart</a>
                        </li>
                    </ul>
                    
                </div>
                
            </nav>
            <div class="container-fluid">
                <div class="mt-2">
                    <partial name="_OperationResult.cshtml" />
                </div>
                @RenderBody()
                <footer>
                    <p>&copy; @DateTime.Now.Year - RentingConstruction Frontend</p>
                </footer>
            </div>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Frontend/Views/Shared/_OperationResult.cshtml
@{
    var type = (string)TempData["_alert.type"];
    var title = (string)TempData["_alert.title"];
    var body = (string)TempData["_alert.body"];
}

<div class="alert-container">
    @if (!string.IsNullOrEmpty(type))
    {
        <div class="alert alert-@type alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>@title</strong> @body
        </div>
    }
</div>